---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible
  namespace: {{ ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ansible
subjects:
- kind: ServiceAccount
  name: ansible
  namespace: {{ ns }}
